plugins {
  id 'net.minecraftforge.gradle' version '6.0.+'
  id 'org.spongepowered.mixin' version '0.7-SNAPSHOT'
  id 'maven-publish'
  id 'eclipse'
}

version = "${mc_version}-${mod_version}"
group = 'com.infamous.dungeons_libraries'
archivesBaseName = "${modid}"

java {
  toolchain {
    languageVersion.set(JavaLanguageVersion.of(17))
  }
}

println('Java: ' + System.getProperty('java.version') + ' JVM: ' + System.getProperty('java.vm.version') + '(' + System.getProperty('java.vendor') + ') Arch: ' + System.getProperty('os.arch'))

minecraft {
  mappings channel: "${mappings_channel}", version: "${mappings_version}"
  accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')

  runs {
    client {
      workingDirectory project.file('run')
      property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
      arg "-mixin.config=${modid}.mixins.json"
      property 'forge.logging.console.level', 'debug'
      property 'mixin.env.remapRefMap', 'true'
      property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"

      mods {
        dungeons_libraries {
          source sourceSets.main
        }
      }
    }

    server {
      workingDirectory project.file('run')
      property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
      property 'forge.logging.console.level', 'debug'
      property 'mixin.env.remapRefMap', 'true'
      property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"

      mods {
        dungeons_libraries {
          source sourceSets.main
        }
      }
    }
  }
}

// Include resources generated by data generators.
sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
  maven { url = "https://maven.minecraftforge.net" }
  maven { url = "https://maven.parchmentmc.org" }
  maven { url = "https://repo.spongepowered.org/repository/maven-public" }
  maven { url = "https://dist.creeper.host/Sponge/maven" }
  maven { url = "https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/" }
  maven { url = "https://maven.theillusivec4.top/" }
  mavenCentral()
}

dependencies {
  minecraft "net.minecraftforge:forge:${mc_version}-${forge_version}"
  annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'

  implementation fg.deobf("software.bernie.geckolib:geckolib-forge-1.19:${geckolib_version}")
  runtimeOnly fg.deobf("top.theillusivec4.curios:curios-forge:${curios_version}")
  compileOnly fg.deobf("top.theillusivec4.curios:curios-forge:${curios_version}:api")

  compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:${mixinextras_version}"))
  implementation(jarJar("io.github.llamalad7:mixinextras-forge:${mixinextras_version}")) {
    jarJar.ranged(it, "[${mixinextras_version},)")
  }
}

mixin {
  add sourceSets.main, "dungeons_libraries.refmap.json"
  config "dungeons_libraries.mixins.json"
}

jar {
  manifest {
    attributes([
      "Specification-Title"     : "Dungeons Libraries",
      "Specification-Vendor"    : "Infamous Mods",
      "Specification-Version"   : "1",
      "Implementation-Title"    : project.name,
      "Implementation-Version"  : "${version}",
      "Implementation-Vendor"   : "Infamous Mods",
      "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
      "MixinConfigs"            : "dungeons_libraries.mixins.json"
    ])
  }
}

jar.finalizedBy('reobfJar')

publishing {
  publications {
    mavenJava(MavenPublication) {
      artifact jar
    }
  }
  repositories {
    maven {
      url "file:///${project.projectDir}/mcmodsrepo"
    }
  }
}
